// Builds the page that runs inside MDView's WebKit view.
//
// Two bundles, on purpose:
//   bundle.js  — markdown, highlighting, sanitising and our own code. Always loaded.
//   mermaid.js — diagrams only. ~10x the size of everything else, so it is a
//                separate file that bundle.js injects when a document has a
//                mermaid block, and never costs anything otherwise.
//
// IIFE, not ESM: the page is loaded from file://, where module scripts are
// blocked by CORS. Plain scripts work, and the CSP allows script-src 'self'.
import * as esbuild from "esbuild";
import { statSync } from "node:fs";

const out = "../Resources";
const watch = process.argv.includes("--watch");

const shared = {
  bundle: true,
  format: "iife",
  target: "safari26", // the WKWebView that ships with the macOS floor in build.sh
  minify: !watch,
  sourcemap: watch ? "inline" : false,
  legalComments: "none",
  logLevel: "info",
};

const builds = [
  {
    ...shared,
    entryPoints: ["src/viewer.js"],
    outfile: `${out}/bundle.js`,
    banner: { js: "/* Generated by web/build.mjs — edit web/src/viewer.js instead. */" },
  },
  {
    ...shared,
    entryPoints: ["src/mermaid.js"],
    outfile: `${out}/mermaid.js`,
    banner: { js: "/* Generated by web/build.mjs — edit web/src/mermaid.js instead. */" },
  },
];

function report() {
  for (const file of ["bundle.js", "mermaid.js"]) {
    const kb = (statSync(`${out}/${file}`).size / 1024).toFixed(0);
    console.log(`  ${file.padEnd(16)} ${kb.padStart(5)} KB`);
  }
}

if (watch) {
  for (const options of builds) {
    const context = await esbuild.context(options);
    await context.watch();
  }
  console.log("watching web/src — rebuilds on save, then ⌘R in the app");
} else {
  await Promise.all(builds.map((options) => esbuild.build(options)));
  report();
}
